### ISSUE TITLE
ToTerbilangString()

### ISSUE THREAD

**Issue by WahidinAji** [vandyahmad24/go-terbilang#1]
ini param `curr` buat apa ya om ?

[line](https://github.com/vandyahmad24/go-terbilang/blob/master/terbilang.go#L83)

**Comment by vandyahmad24** [comment]
buat currency mas jadi  tar hasilnya misal 14850 SGD
EMPAT BELAS RIBU DELAPAN RATUS LIMA PULUH SGD 
gitu

**Comment by WahidinAji** [comment]
ohhh kirain buat apaan, wkwkkw. sipsip, open hacktoberfest coba. gue mau tambahin test casenya sama update `usage` nya wkwkwkw
